services:
  dropit:
    build: .
    container_name: dropit
    ports:
      - '3400:3400'

    environment:
      JWT_SECRET: 'supersecrettestkey'
      PORT: 3400
      ADMIN_PASSWORD: 'Admin123!'

      DATABASE_URL: ''
      STORAGE_DIR: ./uploads

      DOMAIN: ''
      USE_HTTPS: 'false'

    volumes:
      - ./uploads:/app/uploads

    depends_on:
      mysql:
        condition: service_healthy

    restart: unless-stopped

volumes:
  dropit-mysql:
