# fly.toml app configuration file generated for dropit on 2026-08-11T02:20:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dropit'
primary_region = 'fra'

[build]
[env]
  ALLOWED_HOSTS = 'dropit.doomhowl.com'
  DATABASE_URL = '/data/database.db'
  DB_TYPE = 'sqlite'
  NODE_ENV = 'production'
  PORT = '8080'
  STORAGE_DIR = '/data/uploads'
  TRUST_PROXY_HEADERS = 'true'
  USE_HTTPS = 'true'

[[mounts]]
  source = 'dropit_data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
